include "stdlib/jdk/21/amazon.conf"

app {
    machines = [windows.amd64, linux.aarch64, linux.arm64, mac.aarch64]

    display-name = "Chirp"
    fsname = "chirp"
    vendor = "Mobidev Studio"
    description = "Chirp chat application"
    version = "1.0.0"
    rdns-name = "com.example.chirpappkmp"
}